import { existsSync, mkdirSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { systemTimezone } from "@yrm/core";
import { flagList, flagString } from "../argv.ts";
import type { BuiltinCommand, CliEnv } from "../env.ts";

export const CONFIG_FILE = "yrm.config.ts";

export interface InitOptions {
  selfAddresses: string[];
  selfDomains: string[];
  name?: string;
  timezone: string;
  /** Emit `import { defineConfig } from "@yrm/core"`. Off when the package does not resolve from the project. */
  importCore: boolean;
}

const q = (s: string) => JSON.stringify(s);
const list = (xs: string[]) => `[${xs.map(q).join(", ")}]`;

export function renderConfig(o: InitOptions): string {
  const tenant = [
    `    id: "local",`,
    ...(o.name !== undefined ? [`    name: ${q(o.name)},`] : []),
    `    // Your own addresses. Participants matching these (or selfDomains) are marked as "you".`,
    `    selfAddresses: ${list(o.selfAddresses)},`,
    ...(o.selfDomains.length > 0 ? [`    selfDomains: ${list(o.selfDomains)},`] : []),
    `    // IANA timezone used to decide what "today" means.`,
    `    timezone: ${q(o.timezone)},`,
  ];
  const head = o.importCore
    ? [`import { defineConfig } from "@yrm/core";`, ``]
    : [
        `// @yrm/core is not installed in this directory, so the config is a plain object.`,
        `// After \`bun add @yrm/core\` you can wrap it for type checking:`,
        `//   import { defineConfig } from "@yrm/core";`,
        `//   export default defineConfig({ ... });`,
        ``,
      ];
  const open = o.importCore ? "export default defineConfig({" : "export default {";
  const close = o.importCore ? "});" : "};";
  return [
    `// yrm configuration, generated by \`yrm init\`. See yrm.config.example.ts in the YRM repo for every option.`,
    ...head,
    open,
    `  tenant: {`,
    ...tenant,
    `  },`,
    ``,
    `  // The SQLite file lives next to this config. .yrm/local/ is safe to gitignore.`,
    `  storage: { driver: "sqlite", path: ".yrm/local/yrm.sqlite" },`,
    ``,
    `  // Models are chosen by tier, never by name in code. Each tier is a fallback chain:`,
    `  // the router tries each { provider, model } in order and moves on when one is`,
    `  // unreachable or unconfigured.`,
    `  //   triage, extract: cheap and frequent. Defaults to a local Ollama model`,
    `  //     (\`ollama pull qwen3:8b\`). Point it anywhere OpenAI-compatible by changing`,
    `  //     providers["openai-compatible"].baseUrl, or add a hosted hop to the chain.`,
    `  //   synthesize: rare and expensive; sees facts, never whole corpora.`,
    `  // With no model reachable and no API keys set, YRM still works: the rule-based`,
    `  // extractor is used instead and nothing is sent anywhere.`,
    `  // Run \`yrm doctor\` to see what each tier resolves to and what it would cost.`,
    `  models: {`,
    `    routes: {`,
    `      triage: [{ provider: "openai-compatible", model: "qwen3:8b" }],`,
    `      extract: [{ provider: "openai-compatible", model: "qwen3:8b" }],`,
    `      synthesize: [{ provider: "anthropic", model: "claude-opus-5" }],`,
    `    },`,
    `    // monthlyBudgetUsd: 20,`,
    `    // localOnly: true,`,
    `  },`,
    ``,
    `  // Provider settings, keyed by the provider name used in routes.`,
    `  providers: {`,
    `    // Ollama's default endpoint. vLLM, llama.cpp and hosted gateways work too.`,
    `    "openai-compatible": { baseUrl: "http://localhost:11434/v1" },`,
    `    // Keys come from the environment, never from this file.`,
    `    anthropic: { apiKeyEnv: "ANTHROPIC_API_KEY" },`,
    `  },`,
    close,
    ``,
  ].join("\n");
}

function resolvesCore(cwd: string): boolean {
  try {
    Bun.resolveSync("@yrm/core", cwd);
    return true;
  } catch {
    return false;
  }
}

export function initCommand(env: CliEnv): BuiltinCommand {
  return {
    name: "init",
    description: "Write a yrm.config.ts in the current directory",
    usage: "yrm init [--self you@example.com]... [--domain example.com]... [--name Jack] [--timezone Area/City] [--force]",
    needsHost: false,
    async run(ctx) {
      const file = join(env.cwd, CONFIG_FILE);
      if (existsSync(file) && ctx.flags["force"] !== true) {
        ctx.stderr(`${file} already exists; pass --force to overwrite it`);
        return 1;
      }
      const opts: InitOptions = {
        selfAddresses: flagList(env.parsed, "self").map((s) => s.toLowerCase()),
        selfDomains: flagList(env.parsed, "domain").map((s) => s.toLowerCase()),
        timezone: flagString(ctx.flags, "timezone") ?? systemTimezone(),
        importCore: resolvesCore(env.cwd),
      };
      const name = flagString(ctx.flags, "name");
      if (name !== undefined) opts.name = name;

      writeFileSync(file, renderConfig(opts));
      const local = join(env.cwd, ".yrm", "local");
      mkdirSync(local, { recursive: true });
      writeFileSync(join(local, ".gitkeep"), "");

      ctx.stdout(`wrote ${file}`);
      if (opts.selfAddresses.length === 0) {
        ctx.stdout("note: no --self address given; add yours to tenant.selfAddresses so YRM knows which side is you");
      }
      ctx.stdout("next: yrm import <path>   then   yrm today");
      return 0;
    },
  };
}
